CodePlex is shutting down.
DotNetOpenAuth/DotNetOpenAuth pull request #398
Opened 2017-06-01 13:17 UTC by MartinSulcDotCz

2017-06-01 14:26 UTC, AArnott requested changes
Thanks for the update. One correction needed.

2017-06-01 14:26 UTC, AArnott commented on README.md
> +- [Web Protection Library](NuGet https://www.nuget.org/packages/AntiXSS/4.3.0 and Microsoft Download Center http://www.microsoft.com/en-us/download/details.aspx?id=43126 or in .NET 4.0)
The markdown here is encoded incorrectly. You're mixing links and text.

2017-06-02 15:35 UTC, caojinqin commented on README.md
> +- [Web Protection Library](NuGet https://www.nuget.org/packages/AntiXSS/4.3.0 and Microsoft Download Center http://www.microsoft.com/en-us/download/details.aspx?id=43126 or in .NET 4.0)
y

2018-01-11 13:05 UTC, DavidChristiansen approved these changes

2018-01-11 13:05 UTC, merged